version: '3'

services:
  minecraft-db:
    image: mariadb:10
    ports:
      - "8211:3306"
    volumes:
      - ./database/data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=minecraft
    networks:
      - minecraft
    healthcheck:
      test: "mysql -pchangeme -e 'SELECT 1'"
      interval: 10s
      timeout: 10s
      retries: 12

  minecraft-api:
    image: minecraft-api
    build:
      context: minecraft-api
      dockerfile: Dockerfile
      args:
        - DATABASE_PASSWORD=changeme
        - DATABASE_HOST=minecraft-db
        - DATABASE_DB=minecraft
        - APP_HOME=/home/minecraft-api
    ports:
      - "8210:80"
    networks:
      - minecraft
    depends_on:
      minecraft-db:
        condition: service_healthy

  minecraft-front:
    image: minecraft-front
    build:
      context: minecraft-front
      dockerfile: Dockerfile
      args:
        - APP_HOME=/home/minecraft-front
    ports:
      - "8220:80"
    networks:
      - minecraft
    depends_on:
      - minecraft-api
      - minecraft-avatar

  minecraft-avatar:
    image: minecraft-avatar
    build:
      context: minecraft-avatar
      dockerfile: Dockerfile
      args:
        - APP_HOME=/home/minecraft-avatar
    ports:
      - "8230:80"
    networks:
      - minecraft

networks:
  minecraft:
