name: Docker build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./minecraft-api
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t minecraft-api .

  avatar-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./minecraft-avatar
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t minecraft-avatar .

  front-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./minecraft-front
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t minecraft-front .
